FROM rafalsladek/cropcoin:base

ENV CONFIG_FILE "cropcoin.conf"
ENV MASTERNODESETUP 0
ENV ALLWAYSOVERWRITECONFIG 1
ENV WALLETPASS "pleaseChangeMe"
ENV CROPCOINPORT 17720
ENV CROPCOINRPCPORT 17721
ENV CROPCOINUSER cropcoin
ENV CROPCOINHOME "/home/$CROPCOINUSER"
ENV CROPCOINFOLDER "$CROPCOINHOME/.cropcoin"

RUN useradd -m $CROPCOINUSER
RUN mkdir -p $CROPCOINFOLDER && chown -R $CROPCOINUSER: $CROPCOINFOLDER >/dev/null

RUN apt-get update && apt-get install -y curl

WORKDIR $CROPCOINHOME
EXPOSE $CROPCOINPORT $CROPCOINRPCPORT
VOLUME $CROPCOINFOLDER

COPY start.sh .
RUN chmod +x start.sh && chown -R $CROPCOINUSER: start.sh
USER $CROPCOINUSER
ENV PATH $CROPCOINHOME;$PATH

ENTRYPOINT "./start.sh"