FROM rafalsladek/cropcoin:base
LABEL maintainer "rafalsladek <rafalsladek@gmail.com>"

ENV CONFIG_FILE "cropcoin.conf"
ENV MASTERNODESETUP 0
ENV ALLWAYSOVERWRITECONFIG 1
ENV WALLETPASS "pleaseChangeMe"
ENV CROPCOINPORT 17720
ENV CROPCOINRPCPORT 17721
ENV CROPCOINUSER cropcoin
ENV CROPCOINHOME "/home/$CROPCOINUSER"
ENV CROPCOINFOLDER "$CROPCOINHOME/.cropcoin"

RUN useradd -m $CROPCOINUSER
RUN mkdir -p $CROPCOINFOLDER && chown -R $CROPCOINUSER: $CROPCOINFOLDER >/dev/null

RUN apt-get update && apt-get install -y curl

WORKDIR $CROPCOINHOME
EXPOSE $CROPCOINPORT/tcp $CROPCOINRPCPORT/tcp
VOLUME $CROPCOINFOLDER

COPY start.sh $CROPCOINHOME
RUN chmod +x start.sh && chown -R $CROPCOINUSER: start.sh
USER $CROPCOINUSER
ENV PATH $CROPCOINHOME;$PATH
RUN touch $RANDFILE

HEALTHCHECK --interval=2m --timeout=5s --retries=2 \
  CMD $BINARY_FILE -conf=$CROPCOINFOLDER/$CONFIG_FILE -datadir=$CROPCOINFOLDER getinfo 

ENTRYPOINT "./start.sh"